sudo: false
language: cpp
script: make -j2
compiler: g++
install:
  - export CXX="g++-4.8" CC="gcc-4.8"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
